name: Terraform Deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: 6ca44339-750f-4795-9683-d65a412ed32a
          tenant-id: 6980af2f-acfc-4513-ac50-552bcfdb01a0
          subscription-id: 7a3c6854-0fe1-42eb-b5b9-800af1e53d70

      - name: Show subscriptions (debug)
        shell: pwsh
        run: az account list -o table

      - name: Select subscription
        shell: pwsh
        run: az account set --subscription 7a3c6854-0fe1-42eb-b5b9-800af1e53d70

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        shell: pwsh
        working-directory: ./iac-oving3/bootstrap
        run: terraform init
