name: Terraform Deploy

on:
  workflow_dispatch:

permissions:
  id-token: write        # kreves for OIDC
  contents: read

jobs:
  deploy:
    runs-on: windows-latest

    env:
      TF_IN_AUTOMATION: "true"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Verify login
        shell: pwsh
        run: az account show -o table

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform version
        shell: pwsh
        run: terraform version

      - name: Terraform Init
        shell: pwsh
        working-directory: ./iac-oving3/bootstrap
        run: terraform init -input=false

      - name: Terraform Validate
        shell: pwsh
        working-directory: ./iac-oving3/bootstrap
        run: terraform validate

      - name: Terraform Plan
        shell: pwsh
        working-directory: ./iac-oving3/bootstrap
        run: terraform plan -input=false -no-color
